apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: wordpress

namespace: default

images:
- name: mysql
  newName: harbor.navneetv.com/proxy-cache/library/mysql
  newTag: "8.0"
- name: wordpress
  newName: harbor.navneetv.com/proxy-cache/library/wordpress
  newTag: "6.1.1-php8.1-apache"

secretGenerator:
- name: mysql-pass
  literals:
  - password=Passw0rd!

patches:
- target:
    kind: Certificate
    name: wordpress-cert
  patch: |-
    - op: replace
      path: /spec/commonName
      value: wordpress.navneetv.com
    - op: replace
      path: /spec/dnsNames/0
      value: wordpress.navneetv.com
- target:
    kind: HTTPProxy
    name: wordpress
  patch: |-
    - op: replace
      path: /spec/virtualhost/fqdn
      value: wordpress.navneetv.com

resources:
  - namespace.yaml
  - certificate.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - httpproxy.yaml
